### PR TITLE
Improve ECMAScript compatibility.

### PR DESCRIPTION
**Pull request by dop251**
Hi,

This PR includes a couple of fixes to improve ECMAScript compatibility. The added test cases illustrate the issues fixed. Please consider merging.

### CODE REVIEW

**Comment by dlclark** [comment]
Thanks!  Is the goal of this ES5 compatibility?  I'm hoping to find a regression suite of patterns to run for whatever version of Ecmascript this is. 

I'll look this over in detail this afternoon and follow up with any questions I have.

**Comment by dop251** [comment]
The goal is to pass all the current tc39 tests (https://github.com/tc39/test262/tree/master/test/built-ins/RegExp) that have es5id tag. With these fixes applied the tests pass. Also, running the Octane 2.0 test (https://github.com/chromium/octane/blob/master/regexp.js) produces the correct checksum.

**Comment by dop251** [comment]
Maybe a liitle big of background: I'm writing an ECMAScript implementation in Go (an improved alternative to otto (https://github.com/robertkrimen/otto) with the goal of reaching a full compatibility with ECMAScript 5.1. It's not published yet as it's not finished, but it will be eventually.

**Comment by dlclark** [comment]
LGTM.  Committed with some extra tests and simple refactoring as v1.1.1

**Pull request merged**
