### PR TITLE
Support \u{HEX} syntax in ECMAScript with Unicode flag

### PR DESCRIPTION
**Pull request by mstoykov**

### CODE REVIEW

**Comment by mstoykov** [comment]
This was found by a user of a project I worked on and the original regexp is a lot more ... involved and is [here](https://github.com/ajv-validator/ajv-formats/blob/4dd65447575b35d0187c6b125383366969e6267e/src/formats.ts#L63). 

I would like also the input of @dop251 (sorry about pinging you), as I am using this library through [goja](https://github.com/dop251/goja). I don't think this should be "fixed" goja though, but maybe I have missed something.

**Comment by dop251** [comment]
I'm not sure about other modes, but as far as I'm aware the `\u{...}` syntax is supported in ECMAScript regardless of any other flags.

(Note for @dlclark, the `\u{...}` syntax appears to be unique to ECMAScript, others use `\x{...}`)

**Comment by mstoykov** [comment]
@dlclark I also couldn't find this to be a syntax anywhere else ... but to be honest googling `unicode escape sequence` doesn't really give good results :shrug: 

@dop251 I originally saw it is required from https://exploringjs.com/es6/ch_unicode.html#_where-can-escape-sequences-be-used 

And couldn't really find good reference in the actual specification. Now that I tried again I found https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#_ref_20735 seems like the unicode escapes at all should only work when `u` is added :thinking:

**Comment by dop251** [comment]
Yes, you're right, my bad.

**Comment by mstoykov** [comment]
I triple checked on firefox, gjs and nodejs they have the behaviour explained in the first link I gave. 

Looking at the [specification more closely](https://tc39.es/ecma262/multipage/text-processing.html#prod-RegExpUnicodeEscapeSequence) I just now realised that next to one of the lines there is ? and the other is + :facepalm:

So yes this is more or less the expected behaviour. There seem to be more cases to be implemented but this is the one I have hit so lets have only this for now :grimacing: 

> The only other thing I’d ask is some documentation in the readme about what the new Unicode option does.

will try to come up with something, but it likely will be "enables ECMAScript's unicode mode, has no effect without ECMAScript mode enabled as well"

**Pull request merged**
